# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IQVcBAaMv_-ZMS1M_ycwdvc7S-9pG7K
"""

from fastapi import FastAPI
import joblib
import numpy as np

app = FastAPI(title="Churn Prediction API")

model = joblib.load("churn_model.pkl")

@app.get("/")
def home():
    return {"message": "Churn Prediction API is running"}

@app.post("/predict")
def predict(data: dict):
    features = np.array([[
        data["monthly_spend"],
        data["tenure_months"],
        data["support_calls"]
    ]])

    churn_prob = model.predict_proba(features)[0][1]

    return {
        "churn_probability": round(float(churn_prob), 4)
    }