# -*- coding: utf-8 -*-
"""train.model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cdWeP9Ey4c3C0xxNiY7O2xD96s4eYUE
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import joblib

# Sample dataset
data = pd.DataFrame({
    "monthly_spend": [50, 60, 70, 120, 150, 200, 80, 90, 40, 30],
    "tenure_months": [2, 3, 6, 12, 24, 36, 4, 5, 1, 1],
    "support_calls": [3, 1, 0, 1, 0, 0, 2, 1, 4, 3],
    "churn":         [1, 1, 0, 0, 0, 0, 1, 0, 1, 1]
})

# Features and target
X = data[["monthly_spend", "tenure_months", "support_calls"]]
y = data["churn"]

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Save model
joblib.dump(model, "churn_model.pkl")

print("Model saved as churn_model.pkl")

import os
print(os.listdir())